### ISSUE TITLE
Date is allow for clock challenge ?

### ISSUE THREAD

**Issue by sanjayrajsinh** [flutter/flutter_clock#11]
In clock challenge can I add Date for better look ?

**Comment by cookmscott** [comment]
![image](https://user-images.githubusercontent.com/2273452/69366677-d7806400-0c64-11ea-8562-451c4f160a22.png)
My guess is you can choose to include it or not... They said the clock doesn't even need to have numbers, it could be morse code! The leniency makes me think "telling time" is a requirement but weather + date + other info is up to you!

**Comment by jkurtw** [comment]
Yes, you can include the date, since you can get it without making a network request.
