### ISSUE TITLE
ClockCustomizer - "Contestants: Do not edit this."

### ISSUE THREAD

**Issue by shp-alexander-berger** [flutter/flutter_clock#12]
In the ClockCustomizer class are comments that says "Contestants: Do not edit this."
May I create and use my own ClockCustomizer to change the UI? (or update the ClockCustomizer?)

**Comment by maryx** [comment]
What would you like to change about the ClockCustomizer?

The same rules that apply to the clock (e.g. no network requests) also apply to the customizer.

Feel free to edit the default model values while you develop (e.g. update the default weather condition while you build UIs for each weather condition) but remember to revert your changes and submit the original ClockCustomizer with your project.

**Comment by jkurtw** [comment]
ClockCustomizer is provided, so that a user cycle through the various weather conditions, etc. to see how they are handled by the clock. Each submission should have this same set of conditions, which is one reason for not editing them. Please reopen if this still isn't clear.
