### ISSUE TITLE
What should we have in git repository

### ISSUE THREAD

**Issue by edburtnieks-archive** [flutter/flutter_clock#14]
Just wanted to know what should / should not be inside our git repositories.
If we have cloned whole repo does the whole repo with both example clocks, original README.md, flutter_clock_helper directory have to be present in our own repo?

**Comment by colinskow** [comment]
The answer is in the Getting Started guide on the [contest page](https://flutter.dev/clock) under Step 5.

**Comment by jkurtw** [comment]
Correct. See 5d:

"In your \<path-to-repo\>/flutter_clock folder, zip these two folders:
- flutter_clock_helper (unedited)
- \<name\>_clock (your clock)"

**Comment by jkurtw** [comment]
To clarify, your git repo can have whatever you want in it. The zip you submit should have the minimum specified in the Getting Started guide.
