### ISSUE TITLE
Clock Orientation Requirements

### ISSUE THREAD

**Issue by altShiftDev** [flutter/flutter_clock#15]
The image on the contest page (https://flutter.dev/assets/clock/Lenovo-WTM-c2e515298b46c86d73b91c2cfc515eb6ba9a9e601009219245562d5d65c43d7f.png) seems to imply efforts should be concentrated on a landscape clockface, is this true? The rules/faq don't mention orientation preferences. Please confirm.

**Comment by edburtnieks-archive** [comment]
From what I've gathered then yes, the clock should be in landscape orientation.

Taken from https://flutter.dev/clock

---

Design and data notes:
- The ClockModel API with mock data is provided to you. Using this API is optional, but it provides system information such as the brightness mode, weather, and time format.
- **The clock design should use landscape mode, with a 5:3 aspect ratio.**
- You may use Material Design icons.
- All other assets, fonts, icons, images, and so on should be your own, or licensed under a BSD-3, or OFL license (for fonts).
- Your clock should not:
  - Have user interaction (such as tapping, gestures, dragging, mouse, keyboard, and so on).
  - Play audio, including an alarm.
  - Make network requests.
  - Collect data in violation of applicable laws (including privacy laws).
  - Contain copyrighted or trademarked content.

**Comment by jkurtw** [comment]
Thank you, @edburtnieks! Your reference is correct. 

Landscape, please!

**Comment by orgil1230** [comment]
Sample Clocks's orientations are Portrait. Looks like this. N:1
<img width="452" alt="Screen Shot 2019-12-23 at 10 39 21 pm" src="https://user-images.githubusercontent.com/1621761/71356303-e8125a00-25d5-11ea-9302-73c51be22523.png">
Then it should looks like this ? N:2
<img width="768" alt="Screen Shot 2019-12-23 at 10 38 16 pm" src="https://user-images.githubusercontent.com/1621761/71356352-12641780-25d6-11ea-8cdd-9300f3eb898f.png">

Which one ? N1 Or N2 
And application's default orientation should be landscape ? or Judges will rotate themselves ? 

Thank you.
