### ISSUE TITLE
How can I be notified of a theme change (e.g. light to dark)?

### ISSUE THREAD

**Issue by ra9r** [flutter/flutter_clock#16]
The ClockModel currently has all the configuration options except the theme.  What is the best practice for listening for a theme change in the ClockCustomizer?

**Comment by edburtnieks-archive** [comment]
I think it's built inside flutter material package.

There is code snippet inside `digital_clock.dart` file which checks either it's light or dark theme:

`final colors = Theme.of(context).brightness == Brightness.light
        ? _lightTheme
        : _darkTheme;`

**Comment by jkurtw** [comment]
Thanks, @edburtnieks! 

@ra9r I'll close this, but feel free to re-open if you still have issues.
