### ISSUE TITLE
Flutter for web suddenly stops

### ISSUE THREAD

**Issue by Soumyadeep21** [flutter/flutter_clock#17]
when i try to change the location given by the clockHelper class using the textField in web, it suddenly stops working. If I host that clock and I submit the link of it , will it affect my submission.

**Comment by edburtnieks-archive** [comment]
No, it will not affect your submission as it's not required to make it work for web.

**Comment by jkurtw** [comment]
Sounds like a great bug to file for the Flutter team working on web though! If you can create a minimal repro and submit it at https://github.com/flutter/flutter/issues that would be great.
