### ISSUE TITLE
The default given container by the ClockCustomizer.

### ISSUE THREAD

**Issue by Soumyadeep21** [flutter/flutter_clock#18]
The default customizer class gives us a container and its in 5:3 ratio? So if my make my clock within that constraints, its all right ?

**Comment by edburtnieks-archive** [comment]
Yes

**Comment by jkurtw** [comment]
Confirmed.

**Comment by jkurtw** [comment]
To be sure, from https://flutter.dev/clock:
"The clock design should use landscape mode, with a 5:3 aspect ratio."
