### ISSUE TITLE
Flutter Inspector jump to source not working in this Git source

### ISSUE THREAD

**Issue by Akash35pasupathi** [flutter/flutter_clock#19]
I try to debug the UI but flutter Inspector not working 

I tried  following steps but no use,..
>> I check my Flutter environment ,
>> widget tracking disable option  
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/37899801/69496034-a7022980-0ef3-11ea-91e5-440b34066ea4.png">

**Comment by jkurtw** [comment]
Does Inspector work for other projects for you?

**Comment by jkurtw** [comment]
Please re-open or file a new issue, if you are still having problems here.

**Comment by Akash35pasupathi** [comment]
@jkurtw  NOW iTS WORKING fINE ... mAY i kNOW Y iTS hAPND?
