### ISSUE TITLE
flutter third party api

### ISSUE THREAD

**Issue by liodali** [flutter/flutter_clock#20]
can i use any api for real time weather data?

**Comment by edburtnieks-archive** [comment]
You don't have to make requests to an api. The sample, hard coded data for weather is already provided.

Taken from https://flutter.dev/clock:

- **The ClockModel API with mock data is provided to you. Using this API is optional, but it provides system information such as the brightness mode, weather, and time format.**

- Your clock should not:
    - Have user interaction (such as tapping, gestures, dragging, mouse, keyboard, and so on).
    - Play audio, including an alarm.
    - **Make network requests.**
    - Collect data in violation of applicable laws (including privacy laws).
    - Contain copyrighted or trademarked content.

**Comment by jkurtw** [comment]
Right. Your clock should not make network requests. 

The idea is to make it easy to cycle through the various weather conditions to see your designs for each, rather than show the weather of your current location.
