### ISSUE TITLE
Location Permission

### ISSUE THREAD

**Issue by colinskow** [flutter/flutter_clock#21]
I have some ideas to do some cool things based on a rough location. A string isn't enough, I need lat/long coordinates. Is it acceptable to use the location permission on the device? I don't see anything against this in the rules (we aren't collecting the data), but wanted to check.

The other option is to modify ClockCustomizer and add a latitude / longitude field with defaults.

**Comment by jkurtw** [comment]
https://github.com/flutter/flutter_clock/issues/9#issuecomment-557338690 is relevant. 

If you base behavior on device location, then the judges will need to enter lat/long coordinates in the iOS or Android simulator. I think it would be just as straight forward to provide those coordinates in your submission notes and allow them to be entered directly as the location string. 

Make sense?

**Comment by colinskow** [comment]
Yes, that makes sense. I'll just add a note in my submission to enter Lat/Long coordinates in the existing location field. Probably not worth it to embed a 150MB geocoding database.

**Comment by jkurtw** [comment]
Sounds good!
