### ISSUE TITLE
Why by Default setState() is called from flutter_clock_helper Lib 

### ISSUE THREAD

**Issue by sanjayrajsinh** [flutter/flutter_clock#22]
When I TAB on screen `setState()` is called from `ClockCustomizer` class. This class is in `flutter_clock_helper` lib.

Because of  `setState()` is called and animation is set from starting position That's why  animation got problem

**Comment by jkurtw** [comment]
Are you using the TAB key on the keyboard to trigger the animation? Note that on https://flutter.dev/clock it says:

"Your clock should not:
Have user interaction (such as tapping, gestures, dragging, mouse, keyboard, and so on)."

**Comment by jkurtw** [comment]
Feel free to reopen if you are still having an issue.
