### ISSUE TITLE
Screen size

### ISSUE THREAD

**Issue by jfdeveloper92** [flutter/flutter_clock#24]
Does the clock need to be adaptive to screen size? I know it needs to be 5:3.

**Comment by colinskow** [comment]
The 5:3 limitation imposed by ClockCustomizer does look really ugly on widescreen devices. Can we remove this or make it an optional setting? I'd prefer to make a responsive landscape clock that looks good at 5:3 and other aspect ratios as well.

Also, things would look a lot better if ClockCustomizer hides the status bar and enforces landscape view.

**Comment by jfdeveloper92** [comment]
I do think the reason the 5:3 aspect ratio is required is because the Lenovo clocks for this contest is a 5:3 I could be wrong I'm not exactly sure what the aspect ratio is I'm just assuming that based on the contest description.

**Comment by colinskow** [comment]
My question is, do we need to use the forced 5:3 from the starter repo, or is it okay to remove that and allow it to be responsive on various aspect ratios?

**Comment by jfdeveloper92** [comment]
I could be mistaken but I believe the reason 5:3 aspect ratio is required is because the Lenovo clock and smart display probably has a 5:3 ratio

**Comment by jkurtw** [comment]
It will only be judged with 5:3 aspect ration, but if it looks good with others, that's great!
