### ISSUE TITLE
How to run the clock face on a Lenovo Smart Clock

### ISSUE THREAD

**Issue by robinbonnes** [flutter/flutter_clock#25]
Is there any documentation available how to run the clock face on a Lenovo Smart Clock or any other smart clock?

**Comment by janstol** [comment]
Duplicate of #13

**Comment by robinbonnes** [comment]
But if its not possible to get the clock face on the clock, why this competition even is there?

**Comment by ride4sun** [comment]
I have the clock and would like to try it during programming it. What is the point otherwise?

**Comment by jkurtw** [comment]
Yes, this is Duplicate of #13.

However, from flutter.dev/clock, "Some of the clock contest submissions might be integrated into the Lenovo Smart Clock's lineup of clock faces, or used as inspiration for future clock faces!"

**Comment by ride4sun** [comment]
Sorry that was starting out great but if I can not even run my own code on
the device that is really stupid Google.
