### ISSUE TITLE
Flare animations

### ISSUE THREAD

**Issue by imaNNeo** [flutter/flutter_clock#26]
Hi 
Can we use flare animations?

**Comment by imaNNeo** [comment]
or any third party library?

**Comment by edburtnieks-archive** [comment]
Taken from https://flutter.dev/clock FAQ:

**Can I use Flare animations?**
```
Yes, you can use Flare animations in your submission.
```

**Comment by imaNNeo** [comment]
Sorry.
Thanks ;)
