### ISSUE TITLE
Can we fake Weather and Location info?

### ISSUE THREAD

**Issue by shakirkasmani** [flutter/flutter_clock#27]
As this competion is concentrating on clock can we provide fake weather and location information?

**Comment by josephchenghmlet** [comment]
There is already an option to change weather and location via setting.

**Comment by jkurtw** [comment]
Yes, this is provided out of the box in the examples via flutter_clock_helper. Please see the readme here: https://github.com/flutter/flutter_clock/blob/master/flutter_clock_helper/README.md
