### ISSUE TITLE
Video Playing in background for few second.

### ISSUE THREAD

**Issue by satishsoni777** [flutter/flutter_clock#28]
Can I play a video, behind the clock for a few seconds? using stack.

**Comment by josephchenghmlet** [comment]
It should be allowed. Ensure that the video dependency works for fuschia.
And if you are using open source or downloaded video, make sure the source license is valid.

**Comment by jkurtw** [comment]
As long as you have the video packaged with your app (don't need internet to fetch it) and the license checks out, then you are fine. It doesn't need to work on Fuchsia :-)
