### ISSUE TITLE
Screen size

### ISSUE THREAD

**Issue by dheerajv09** [flutter/flutter_clock#29]
Does analog_clock/ digital_clock follows 5:3 aspect ratio

**Comment by jfdeveloper92** [comment]
Yes, if you use the clock helper package provided in the samples it is using the 5:3 aspect ratio.

**Comment by jkurtw** [comment]
Correct!

**Comment by kawal7415** [comment]
I have a question regarding this that Lenovo Smart Display always works in landscape mode ?

If yes, it means that the width > height ?

Am I right ?
