### ISSUE TITLE
clock type 

### ISSUE THREAD

**Issue by Abdullahi-1998** [flutter/flutter_clock#30]
should the clock i build be analog or digital or it doesn't matter which one i build

**Comment by josephchenghmlet** [comment]
It can also be in binary clock!

**Comment by jkurtw** [comment]
From the FAQ at https://flutter.dev/clock

_**Does the clock have to show the time?**
The viewer should be able to tell the time. Whether that be with digits, clock hands, a sundial shadow, or colors flashing in Morse code, there should be some way for a user to reliably determine the time. (It’s OK if telling the time requires some thinking.)_

So, you can do whatever you want as long as there is some way to derive time :-)
