### ISSUE TITLE
GNU GPL (Free for Commercial Use)

### ISSUE THREAD

**Issue by JonathanMonga** [flutter/flutter_clock#32]
Can I use GNU GPL (Free for Commercial Use) font??? Or only OFL is recommended

**Comment by jkurtw** [comment]
I can only reference what is in the [official rules](https://docs.google.com/document/d/1ybyQCK8Sy7vrD9wuc6pbgwVkyrVZ7Rd_41r5NXGqlt8/edit):
_11. INTELLECTUAL PROPERTY RIGHTS:  By submitting a Submission in this Contest, the entrant warrants and represents that the Submission, including the programming and related material, is open source and is released subject to an appropriate open source license (for code, BSD aka University of California license, MIT license or Apache 2.0 license are recommended; for assets, CC BY 4.0 license or Apache 2.0 license are recommended; for fonts, OFL license is recommended), and not subject to the proprietary rights of any person or entity._
