### ISSUE TITLE
changes to the clock

### ISSUE THREAD

**Issue by rvamsikrishna** [flutter/flutter_clock#33]
I have submitted a clock. But have to make a few minor changes. In the faqs, it is mentioned

> Yes, as long as your changes occur before January 20th, 11:59pm PST (GMT - 8).

Is making these changes only on the GitHub repo enough or the codebase should be zipped and resubmitted.

**Comment by jkurtw** [comment]
You should zip and resubmit. We will only consider the latest submission from your email address.
