### ISSUE TITLE
Are we allowed to add options in settings?

### ISSUE THREAD

**Issue by benwulmer** [flutter/flutter_clock#34]
For instance, could we add a slider to change clock brightness?

**Comment by jkurtw** [comment]
Sorry, no. This would effectively be an escape hatch for the following rule at flutter.dev/clock:

_Your clock should not:_

_- Have user interaction (such as tapping, gestures, dragging, mouse, keyboard, and so on)._

**Comment by meDerek18** [comment]
But, what if i wanted to have an option, say, to go to analogue clock for any reason. That is not going to allow such as tapping, just a change in what the clock looks like?? eg , my great aunt is visiting and she likes to see numbers
