### ISSUE TITLE
Two pixels border on customizer.dart

### ISSUE THREAD

**Issue by ma-altaiir** [flutter/flutter_clock#35]
If we try to pixel perfect fill a container with tiles inside the 5/3 aspect ratio, there will be an overflow since customizer.dart contains a 2.0 pixels border. `@override
  Widget build(BuildContext context) {
    final clock = Center(
      child: AspectRatio(
        aspectRatio: 5 / 3,
        child: Container(
          decoration: BoxDecoration(
            border: Border.all(
              width: 2,
              color: Theme.of(context).unselectedWidgetColor,
            ),
          ),
          child: widget._clock(_model),
        ),
      ),
    );`

Can we change that one or please change it  and make container background grey for visibility instead of a border.

**Comment by orgil1230** [comment]
yeah i've deleted the border already.  Is it fine ?

**Comment by jkurtw** [comment]
Yes, feel free to remove the border.
