### ISSUE TITLE
Sunrise and sunset times should be added to the clock model

### ISSUE THREAD

**Issue by bdvir** [flutter/flutter_clock#38]
Daylight hours information may be important even more than weather for many users. 

The user will decide which interface to use and how to customize it, but as a clock interface developer, I need this info without network requests.

Could sunrise and sunset times be added to the clock model?

**Comment by jkurtw** [comment]
This is a great suggestion. Feel free to package sunrise/sunset times for specific locations with your submission and provide instructions to the judges on which locations to test. However, this will be time dependent, so please be sure to capture any key features in your demo video (see submission form that asks for a video)
