### ISSUE TITLE
Flutter Clock Challenge related question

### ISSUE THREAD

**Issue by justkawal** [flutter/flutter_clock#39]
I have a question regarding this that Lenovo Smart Display always works in landscape mode ?

If yes, it means that the width > height ?

Am I right ?

**Comment by ma-altaiir** [comment]
You do have a helper package that is enforcing a 5 : 3 aspect ratio in lanscape mode, you do have width > height

**Comment by jkurtw** [comment]
Correct. From flutter.dev/clock:
"The clock design should use landscape mode, with a 5:3 aspect ratio."

The example code in this repo also uses the same.
