### ISSUE TITLE
google_fonts package

### ISSUE THREAD

**Issue by jfdeveloper92** [flutter/flutter_clock#40]
Can I use the new google_fonts package to set fonts in my app? Since the are "fetched once via http at runtime" would it disqualify due to the fetch from internet part?

**Comment by justkawal** [comment]
No, You can't make network calls as it has been clearly stated in the rules and guidelines:

Your clock should not:

- Have user interaction (such as tapping, gestures, dragging, mouse, keyboard, and so on).

- Play audio, including an alarm.

- Make network requests.

- Collect data in violation of applicable laws (including privacy laws).

- Contain copyrighted or trademarked content.

**Comment by skhalsa10** [comment]
you can still download the physical fonts files and package them in the app that way. You will not be making any network calls this way.

**Comment by jkurtw** [comment]
Please package the fonts with your app
