### ISSUE TITLE
Certain submission requirements not understood

### ISSUE THREAD

**Issue by BombeyR-zz** [flutter/flutter_clock#42]
Hello Google.
Thanks for organizing such a contest. 
I am a Flutter novice and there are certain issues I have not quite understood with the submission requirements 

- The clock face developed should not have user interaction (such as tapping, gestures, dragging, mouse, keyboard, and so on) but once I run the initial digital clock I get a settings Icon on tap. That I don't really understand.

- The clock seems to depend a lot on the flutter_clock_helper directory but I don't quite understand why, since we are expected to submit this directory unedited. I actually don't really understand the importance of the flutter_clock_helper directory.

-Next, the submitted clock should show only the time as indicated but the customizer.png  image in the flutter clock helper directory shows other parameters such as temperature. 
Please, I will like to have a more detailed explanation of the contest submission requirements in general and also on the flutter_clock_helper directory.
Thanks in advance.
Ronny.

**Comment by skhalsa10** [comment]
I have not gotten that far into the details but I think maybe just don't make it interactive. settings are not really interactive. but maybe they change it from a light theme to a dark theme. interactivity is like don't turn the clock into a game.

I just started looking at this as well. and it seems that the flutter_clock_helper directory is imported into the analog and digital apps. look in the main.dart file on the analog or digital project 
![image](https://user-images.githubusercontent.com/15662035/71235118-7924c080-22b8-11ea-984f-246725d4184d.png)

there seems to be stuff in here related to what makes up the settings that you also mentioned above.
![image](https://user-images.githubusercontent.com/15662035/71235223-c5700080-22b8-11ea-8d24-97f175ac4084.png)


hope that helps :)

**Comment by BombeyR-zz** [comment]
Okay, thanks a lot. I will look into that.

**Comment by jfdeveloper92** [comment]
@BombeyR where do you see the "the submitted clock should show only the time as indicated" listed in the requirements?

**Comment by jkurtw** [comment]
I think the best summary is that you should not make the clock face itself respond to touch events. If you want the clock to respond to settings changes, then you can use flutter_clock_helper which has these controls available for you.
