### ISSUE TITLE
Using Assets which requires attribution

### ISSUE THREAD

**Issue by tirth-aubergine** [flutter/flutter_clock#45]
Can I use part of this asset in my clock? 

https://www.vecteezy.com/vector-art/85439-free-forest-landscape-with-flock-of-birds-vector

Thanks.

**Comment by tirth-aubergine** [comment]
Also, can I use flare (rive) assets made by others?

https://rive.app/explore

**Comment by JonathanMonga** [comment]
Check FACs for more informations...You must create all assets.

**Comment by jkurtw** [comment]
You do not need to create them, but they must have an appropriate license. See flutter.dev/clock:
_"Your Submission’s code must be licensed under an appropriate open source license (for code, BSD aka University of California license, MIT license or Apache 2.0 license are recommended; for assets, CC BY 4.0 license or Apache 2.0 license are recommended; for fonts, OFL license is recommended)."_
