### ISSUE TITLE
is default orientation landscape ?

### ISSUE THREAD

**Issue by orgil1230** [flutter/flutter_clock#46]
Sample Clocks's orientations are Portrait. Looks like this. N:1
<img width="452" alt="Screen Shot 2019-12-23 at 10 39 21 pm" src="https://user-images.githubusercontent.com/1621761/71356303-e8125a00-25d5-11ea-9302-73c51be22523.png">
Then it should looks like this ? N:2
<img width="768" alt="Screen Shot 2019-12-23 at 10 38 16 pm" src="https://user-images.githubusercontent.com/1621761/71356352-12641780-25d6-11ea-8cdd-9300f3eb898f.png">

Which one ? N1 Or N2 
And application's default orientation should be landscape ? or Judges will rotate themselves ? 

Thank you.

**Comment by JonathanMonga** [comment]
That's not a problem...
But it must work in both orientation

**Comment by skhalsa10** [comment]
I think also just make sure that you can handle the aspect ratio 5/3

**Comment by jkurtw** [comment]
The judges will look at your entry in landscape orientation. From flutter.dev/clock:
_"The clock design should use landscape mode, with a 5:3 aspect ratio."_

**Comment by orgil1230** [comment]
> The judges will look at your entry in landscape orientation. From flutter.dev/clock:
> _"The clock design should use landscape mode, with a 5:3 aspect ratio."_

thank you
