### ISSUE TITLE
Temperature?

### ISSUE THREAD

**Issue by ciriousjoker** [flutter/flutter_clock#47]
Settings give the possibility to set Celsius vs Fahrenheit, but what's the point of it if there's no way to get temperature information in the first place since network requests are forbidden?

**Comment by JonathanMonga** [comment]
You must use flutter_clock_helper that provide the temperature informations

**Comment by ciriousjoker** [comment]
wtf I'm stupid... Didn't even look if there was a property. I just assumed that because you can't change it, it doesn't exist.
