### ISSUE TITLE
Flutter clock helper

### ISSUE THREAD

**Issue by ShalikaAshan01** [flutter/flutter_clock#48]
Can I edit the flutter clock helper class?

**Comment by orgil1230** [comment]
> Can I edit the flutter clock helper class?

i already clear the border. But you can't edit other things i think so.

**Comment by skhalsa10** [comment]
> Can I edit the flutter clock helper class?

No, that class has comments saying do not edit it.

I mean I guess you could but I wouldn't just in case.

**Comment by jkurtw** [comment]
You cannot add new options, if that is what you are asking. What type of edits do you have in mind?

**Comment by ShalikaAshan01** [comment]
> You cannot add new options, if that is what you are asking. What type of edits do you have in mind?

yeah, I mean adding new options.
