### ISSUE TITLE
Flutter Clock from scratch

### ISSUE THREAD

**Issue by lokesh051** [flutter/flutter_clock#49]
is it mandatory to use the flutter clock helpers or download the flutter clock repository.  Can i start from scratch?

**Comment by JonathanMonga** [comment]
You can start from scratch...
But its recommended to use flitter_clock_helper

**Comment by lokesh051** [comment]
if I am starting from scratch then do I have to include the flutter_helper directory in my project although I am not using it anywhere. I can see in the submission requirements it's mentioned something like this 
"In your <path-to-repo>/flutter_clock folder, zip these two folders:
flutter_clock_helper (unedited)
<name>_clock (your clock)"

**Comment by JonathanMonga** [comment]
You can submit one directory if you create your own clock that don't use flutter_clock_helpers

**Comment by jkurtw** [comment]
flutter_clock_helper is not required for your submission to be valid. It is there to give you access to the optional parameters, like light or dark mode. However, you can submit a project that does not use it at all.
