### ISSUE TITLE
Other licenses than BSD-3 ?

### ISSUE THREAD

**Issue by Maistho** [flutter/flutter_clock#5]
Hi,

I'm wondering if other freely available assets can be used, such as images that are licensed CC0 or CC-BY?

The rules state that any assets need to be licensed under BSD-3, but it would make sense for me that I should be able to use assets licensed under for example CC0.

**Comment by jkurtw** [comment]
Asking legal... please hold :-)

**Comment by jkurtw** [comment]
Adding CC 4.0 to the list here.

**Comment by Maistho** [comment]
Thanks, I saw that the rules doc has been updated to read:
> Your Submission’s code must be licensed under an appropriate open source license (for code, BSD aka University of California license, MIT license or Apache 2.0 license are recommended; for assets, CC BY 4.0 license or Apache 2.0 license are recommended; for fonts, OFL license is recommended).

Does this mean that other open licenses might also be valid, such as [the unsplash license](https://unsplash.com/license)?

**Comment by Maistho** [comment]
Also, the website has not been updated and still reads:
> All other assets, fonts, icons, images, and so on should be your own, or licensed under a BSD-3, or OFL license (for fonts).

**Comment by jkurtw** [comment]
flutter.dev/clock has been updated to read:

> Your Submission’s code must be licensed under an appropriate open source license (for code, BSD aka University of California license, MIT license or Apache 2.0 license are recommended; for assets, CC BY 4.0 license or Apache 2.0 license are recommended; for fonts, OFL license is recommended).
