### ISSUE TITLE
Submission

### ISSUE THREAD

**Issue by lokesh051** [flutter/flutter_clock#50]
I submitted my clock but now how do I get the confirmation that I am in the contest

**Comment by JonathanMonga** [comment]
For now there's not confirmation...
I think it will come at the end of contest.

**Comment by JonathanMonga** [comment]
Check the FAQs for more informations...

**Comment by lokesh051** [comment]
ughh..

**Comment by emilysmithson** [comment]
Same here! How do I know they've received it?

**Comment by jkurtw** [comment]
If you submitted the form and didn't get an error, then you are in the competition :-)
