### ISSUE TITLE
Second Hand display issue in the Analog clock

### ISSUE THREAD

**Issue by talamaska** [flutter/flutter_clock#51]
I'm not sure if this was made on purpose, but the default analog clock seconds hand is going out of boundaries of the clock. I noticed that when drawing the hands, the strokeCap is set to square, so in the end the hand size is bigger than expected, since the size of the seconds is set to the half of the shortest side. I guess the hands are customize-able  and we can put there whatever we want.

**Comment by JonathanMonga** [comment]
Yes, you can customize the hands clock
