### ISSUE TITLE
Self made font license

### ISSUE THREAD

**Issue by nilpntr** [flutter/flutter_clock#53]
Do i have to provide a license for a self made font?

**Comment by JonathanMonga** [comment]
Yes,

**Comment by jkurtw** [comment]
Yes, please provide a license file if you created the font. From flutter.dev/clock:
- _Your Submission’s code must be licensed under an appropriate open source license (for code, BSD aka University of California license, MIT license or Apache 2.0 license are recommended; for assets, CC BY 4.0 license or Apache 2.0 license are recommended; for fonts, OFL license is recommended)._
