### ISSUE TITLE
Extension functions

### ISSUE THREAD

**Issue by kazume** [flutter/flutter_clock#54]
Is there any limit on which version of dart can be used? Or the real question is: can extension functions be used, requiring dart 2.6.0?

**Comment by JonathanMonga** [comment]
Extension methods is a feature of Dart 2.7.0, I think...

**Comment by kazume** [comment]
I read both, but when implementing an extension function in flutter, it warns me that it needs the SDK set to 2.6.0 or higher, so I assumed this was the correct requirement for using extension functions :)

**Comment by kazume** [comment]
No one? Anyone? :)

**Comment by SirusCodes** [comment]
i guess you can use it because your clock face should run on latest flutter sdk

**Comment by DeepStyles** [comment]
lol I had same doubt, whts the answer???

**Comment by kazume** [comment]
Not sure ... I used it (on basis of what SirusCodes said). Hope to get an official answer before the 20th though.

**Comment by jkurtw** [comment]
As long as your project can build and run with Flutter 1.12 (stable channel) then you are fine.
