### ISSUE TITLE
Which time format is required ?

### ISSUE THREAD

**Issue by justkawal** [flutter/flutter_clock#55]
We have to build the clock for both 24 hour and 12 hour format ?

Or only for anyone format ??

**Comment by JonathanMonga** [comment]
That's your own decision...
Because the flutter_clock_helpers provide this feature.

**Comment by justkawal** [comment]
Which means that I can choose If I desire to build it for 24 or 12 hour format ?

Telling time in both format is not necessary for the Contest ??

**Comment by orgil1230** [comment]
> Which means that I can choose If I desire to build it for 24 or 12 hour format ?
> 
> Telling time in both format is not necessary for the Contest ??

Did you try sample clocks ? flutter_clock_helpers provide this feature. Pls try the sample clocks first.

**Comment by jkurtw** [comment]
Any format is fine. If you want to provide both, then flutter_clock_helper has a mechanism to do this.
