### ISSUE TITLE
Can't run the final submission with the steps specified on the flutter.dev/clock !!

### ISSUE THREAD

**Issue by justkawal** [flutter/flutter_clock#56]
![Screenshot 2020-01-03 at 9 17 09 AM](https://user-images.githubusercontent.com/49296873/71706319-20057280-2e0a-11ea-98bb-d6832cfd9f1b.png)

- In your (name)_clock directory, reduce the clock’s size.
   * Delete the (name)_clock/ios, (name)_clock/android, and (name)_clock/web (if present) folders.
   * Run flutter clean.

- In your (path-to-repo)/flutter_clock folder, zip these two folders:
   * flutter_clock_helper (unedited)
   * (name)_clock (your clock)

- Verify that your (project).zip file works, using the following steps:
   `flutter channel stable`
   `flutter upgrade`
   `unzip (project).zip`
   `cd (name)_clock`
   `flutter create .`
   `flutter run (on Android or iOS in landscape)`

After the 3rd Command i.e. ( `unzip (project).zip` )
we should run
`unzip (name)_clock.zip`
`unzip flutter_clock_helper.zip`

As we have already zipped the **flutter_clock_helper** and **(name)_clock** inside **(path-to-repo)/flutter_clock**

Am I going right ?

**Comment by JonathanMonga** [comment]
You must zip your (name)_clock and flutter_clock_helpers in the same folder.

**Comment by justkawal** [comment]
We should run the below commands after `unzip (project).zip` because the below 2 folders are zipped already but on the flutter.dev/clock it is not mentioned
`unzip (name)_clock.zip`
`unzip flutter_clock_helper.zip`

**Comment by JonathanMonga** [comment]
d. In your <path-to-repo>/flutter_clock folder, zip these two folders: flutter_clock_helper (unedited) <name>_clock (your clock)

**Comment by secretwpn** [comment]
What about licensing then? We should have `MIT` or `Apache 2.0` as a license for our submission, but can we still include `flutter_clock_helper` - it doesn't have a license file itself, and I do not recognize the license of its parent folder by its text.

**Comment by jkurtw** [comment]
Right. You should end up with something like:
/my_project/flutter_clock_helper (unedited) 
/my_project/my_clock (your clock)

Zip up my_project. Then, the instructions should work. The goal is just to make sure it's not difficult for the judges to figure out how to run your project. 

@secretwpn `flutter_clock_helper` is covered by https://github.com/flutter/flutter_clock/blob/master/LICENSE

**Comment by talhakhan1297** [comment]
I used google fonts package for fonts, How can I get these fonts OFL licensed? and for code is the existing license file enough? (I don't know anything about licensing code or fonts please explain)

**Comment by talhakhan1297** [comment]
```
flutter channel stable
flutter upgrade
unzip (project).zip
cd (name)_clock
flutter create .
flutter run
```
After the 3rd Command i.e. ( unzip (project).zip )
we should run 
`cd <project>/<name>_clock`

Is this right or I am doing something wrong?

**Comment by jkurtw** [comment]
@talhakhan1297 yes, you are right.
