### ISSUE TITLE
Clarification regarding Background

### ISSUE THREAD

**Issue by karthikraju1** [flutter/flutter_clock#57]
Hi,

As per FAQ, I understand that the Lenovo Smart Clock animates the dark and light theme background based on room's brightness. But can we replace that with any designer background  i.e. both light and dark variants of designer background.
This is basically replacing the default black and light blue colour backgrounds with the dark and light designer backgrounds.
Kindly let me know whether this is allowed or not

**Comment by JonathanMonga** [comment]
Your are free... to make your design.

**Comment by jkurtw** [comment]
Yes, you can do what you want here!
