### ISSUE TITLE
Question about multiple submissions

### ISSUE THREAD

**Issue by AniketMalik** [flutter/flutter_clock#58]
I have created more than 2 clock face UI for the contest.

My question is: "Can I submit both of these clock face UI under two different email address? To be more clear can i submit one clock face UI under 1st email address that i have and another using my other email address ?".

Is it against the rules to use two different email address to submit more than one clock face UI?

**Comment by JonathanMonga** [comment]
You can do that...
But it not recommended

**Comment by jkurtw** [comment]
The requirement is that each individual should only have one submission.
