### ISSUE TITLE
Is using the Clock Customizer mandatory?

### ISSUE THREAD

**Issue by benthillerkus** [flutter/flutter_clock#63]
I don't really like the bars that it adds + it breaks `SystemChrome.SetEnabledSystemUIOverlays([])` (for making the clock run fullscreen on my Android devices). Do we have to use it?

**Comment by ptaranat** [comment]
I felt the same way and included that bar hiding statement in my clock widget. I didn't have to modify any of the helper clock code.

**Comment by jkurtw** [comment]
No, you don't have to use it. Also see #35
