### ISSUE TITLE
How Can I Use this ClockModel .. its have 16 dp padding by default 

### ISSUE THREAD

**Issue by Akash35pasupathi** [flutter/flutter_clock#65]
getting Overflowed 
![image](https://user-images.githubusercontent.com/37899801/72241590-2fa46880-360d-11ea-8e58-30e8cca57b4c.png)

while using this .. 
ClockCustomizer((ClockModel model) => DigitalClock(model)

**Comment by JonathanMonga** [comment]
Its not obligatory to use ClockModel... You can define your own...

**Comment by jkurtw** [comment]
Also see #35
