### ISSUE TITLE
Use of external packages?

### ISSUE THREAD

**Issue by ptaranat** [flutter/flutter_clock#66]
The official rules indicate that Material Design icons are permitted. Since I require weather icons, can I use external icon packages such as Cuptertino or flutter_weather_icons? Alternately, I can just make my own.

Similarly, simple_animatioms provides a MultiTrackTween which is extremely useful for syncing several Tweens. Can I use this package that is MIT licensed?

I'm assuming all packages will be bundled with the submission so no network calls will be required.

**Comment by JonathanMonga** [comment]
You can add other packages...
