### ISSUE TITLE
licence 

### ISSUE THREAD

**Issue by SirusCodes** [flutter/flutter_clock#67]
I built my project upon the provided one, I'm confused how I need to do licences I'm new to opensource. 
Can someone help me with an example.

**Comment by JonathanMonga** [comment]
You just keep the same license...

**Comment by DeepStyles** [comment]
Hi im using opensource fonts, still need license???

**Comment by JonathanMonga** [comment]
Yes, it will need license... OFL it recommended

**Comment by Vishnukvsvk** [comment]
Does .ttf require license. I kept the license they gave and uploaded.Is there a problem?

**Comment by SirusCodes** [comment]
> Does .ttf require license. I kept the license they gave and uploaded.Is there a problem?

yes you need to add licence

**Comment by shakirkasmani** [comment]
I am using google_fonts pub package do I need font license?

**Comment by SirusCodes** [comment]
> I am using google_fonts pub package do I need font license?

You can't use google fonts #40
