### ISSUE TITLE
Is accelerometer usage allowed?

### ISSUE THREAD

**Issue by amuhaimin02** [flutter/flutter_clock#7]
Rule says that no direct user interaction like user taps gestures are allowed. But is it permitted to include some indirect interaction by taking reading from accelerometer and gyroscope to determine the orientation of the device and detect user shakes and react according to it?

**Comment by jkurtw** [comment]
Cool idea! You can use the accelerometer, but it will not be considered by the judges. The key experiences should not solely depend on it and be possible without the accelerometer as well.
