### ISSUE TITLE
submission confirmation

### ISSUE THREAD

**Issue by benedicte69** [flutter/flutter_clock#71]
When submitting, are we receiving a confirmation by mail of the submission(s) because I do not have any

**Comment by lokesh051** [comment]
check this out
https://github.com/flutter/flutter_clock/issues/50

**Comment by benedicte69** [comment]
Thanks a lot,  that is logical in case you send several projects as the last sending is retained. But it leave you in some sort of incertitude ... 

Envoyé depuis Yahoo Mail pour Android 
 
  Le ven., janv. 17, 2020 à 7:53, lokesh051<notifications@github.com> a écrit :   
check this out
#50

**Comment by benedicte69** [comment]
oups , sorry I mean 'leaves you in some sort of uncertainty '

Envoyé depuis Yahoo Mail pour Android 
 
  Le ven., janv. 17, 2020 à 12:00, Benedicte<notifications@github.com> a écrit :   Thanks a lot,  that is logical in case you send several projects as the last sending is retained. But it leave you in some sort of incertitude ... 

Envoyé depuis Yahoo Mail pour Android 
 
 Le ven., janv. 17, 2020 à 7:53, lokesh051<notifications@github.com> a écrit : 
check this out
#50

**Comment by lokesh051** [comment]
I had submitted earlier but can I re submit the same thing? Just to be sure

**Comment by benedicte69** [comment]
I have made 2 submissions because the first time I pick up on my desk the wrong video . But it was for the same clock...  Now for sure if you change your code it is clear it will be the last one which will be taken according to the submission rules... 

Envoyé depuis Yahoo Mail pour Android 
 
  Le ven., janv. 17, 2020 à 13:43, lokesh051<notifications@github.com> a écrit :   
I had submitted earlier but can I re submit the same thing?

**Comment by orgil1230** [comment]
Yes i think it’s possible. I had submitted 2 times last week and I re submitted yesterday 3rd time same email.

**Comment by benedicte69** [comment]
Do you mean you received a confirmation?

Envoyé depuis Yahoo Mail pour Android 
 
  Le sam., janv. 18, 2020 à 3:14, Bat-Orgil Erdenebat<notifications@github.com> a écrit :   
Yes i think it’s possible. I had submitted 2 times last week and I re submitted yesterday 3rd time same email.

**Comment by benedicte69** [comment]
I have tried again and again but I have never never never received any mail....! I would appreciate knowing why?
    Le samedi 18 janvier 2020 à 03:17:18 UTC+1, Benedicte <notifications@github.com> a écrit :  
 
 Do you mean you received a confirmation?

Envoyé depuis Yahoo Mail pour Android 
 
 Le sam., janv. 18, 2020 à 3:14, Bat-Orgil Erdenebat<notifications@github.com> a écrit : 
Yes i think it’s possible. I had submitted 2 times last week and I re submitted yesterday 3rd time same email.

**Comment by orgil1230** [comment]
Oh I’m sorry It’s confused.  I didn’t get confirmation email. Just i used my same email re submit google form. They recommended you can replace your project and they will get your last one. Don’t worry about confirmation email.

**Comment by jkurtw** [comment]
We have a lots of responses. If you submitted the form, we have it!

**Comment by benedicte69** [comment]
I quote: 'All complete and valid submissions will receive a digital certificate of completion'.  So having received nothing I consider I am no longer involved in the so-called challenge. That's sound logical

    Le dimanche 19 janvier 2020 à 22:34:36 UTC+1, jkurtw <notifications@github.com> a écrit :  
 
 
We have a lots of responses. If you submitted the form, we have it!

**Comment by jkurtw** [comment]
That is referring to a certificate you will receive some time after the competition has ended, once we verify your submission is valid. Unfortunately, the Google Form used for submissions was not configured to send you a copy when you submit.

**Comment by benedicte69** [comment]
Thank you for taking the time to answer... but the contest deadline was over today, wasn't it? 
    Le dimanche 19 janvier 2020 à 23:58:37 UTC+1, jkurtw <notifications@github.com> a écrit :  
 
 
That is referring to a certificate you will receive some time after the competition has ended, once we verify your submission is valid. Unfortunately, the Google Form used for submissions was not configured to send you a copy when you submit.

**Comment by jkurtw** [comment]
It ends tomorrow at 11:59pm Pacific. From flutter.dev/clock:
- Submit your final clock
<https://docs.google.com/forms/d/e/1FAIpQLSeWVdnocPZFH-xafvHddPY0o1SZj8EW4E5vVvJp1VfW5Ed1YQ/viewform>
by
January 20th, 11:59pm PST (GMT-8)

**Comment by benedicte69** [comment]
ah ok, only tomorrow .... So I wait to see how things will clarify. Thanks
    Le lundi 20 janvier 2020 à 01:30:06 UTC+1, jkurtw <notifications@github.com> a écrit :  
 
 It ends tomorrow at 11:59pm Pacific. From flutter.dev/clock:
- Submit your final clock
<https://docs.google.com/forms/d/e/1FAIpQLSeWVdnocPZFH-xafvHddPY0o1SZj8EW4E5vVvJp1VfW5Ed1YQ/viewform>
by
January 20th, 11:59pm PST (GMT-8)

**Comment by jkurtw** [comment]
But to be clear, the certificates will be sent later, not right after the
contest closes.
