### ISSUE TITLE
Multiple clock faces

### ISSUE THREAD

**Issue by shinyford** [flutter/flutter_clock#72]
Hi 

I want to submit a clock engine that is easily configured to a wide range of clock faces. Its current build has three example faces, and cycles between them, spending a short period of time on each.

To me, this is a single submission - the clock is in the coding of the engine rather than the three faces' designs. However, I just wanted to check that it wasn't going to be considered a multiple submission somehow: obviously, I don't want to submit something that's ineligible.

Could you please confirm/deny that this would be a valid submission?

Many thanks.

**Comment by jkurtw** [comment]
Yes, this sounds valid!

**Comment by shinyford** [comment]
That's great to hear - thanks for the reply.
