### ISSUE TITLE
Can't run the final submission with the steps specified on the flutter.dev/clock

### ISSUE THREAD

**Issue by talhakhan1297** [flutter/flutter_clock#74]
```
flutter channel stable
flutter upgrade
unzip (project).zip
cd (name)_clock
flutter create .
flutter run
```
After the 3rd Command i.e. (`unzip (project).zip` )
we should run
`cd <project>/<name>_clock`

Is this right or I am doing something wrong?

**Comment by Maistho** [comment]
It depends on how you have created the .zip-file, in your case I assume it contains a single folder containing `flutter_clock_helper` and `(name)_clock`, but in the instructions they asume that it contains those two folders without a wrapping folder. I assume either way is acceptable.

**Comment by talhakhan1297** [comment]
> It depends on how you have created the .zip-file, in your case I assume it contains a single folder containing `flutter_clock_helper` and `(name)_clock`, but in the instructions they asume that it contains those two folders without a wrapping folder. I assume either way is acceptable.

Thank you for your answer. 👍
