### ISSUE TITLE
Screen size to be used for judging

### ISSUE THREAD

**Issue by nishantg95** [flutter/flutter_clock#77]
Apart from providing Android/iOS preference, are we also allowed to provide a specific device to test it on (for example : Google Pixel XL, or iPad Air, or iPhone 11).

Or, are the judges planning to use specific emulators to mock the screen of Lenovo Smart Clock?

Our current clock changes behavior based on screen size. Should we be concerned about making the clock look the same on all devices using a 5:3 box?

**Comment by jkurtw** [comment]
The most most important modality will be 5:3 aspect ratio on the common emulators (e.g. Pixel and iPhone 11). If the judges should try another device or screen size, you can mention it on the submission form.
