### ISSUE TITLE
Question: is provider or flutter_bloc packages allowed?

### ISSUE THREAD

**Issue by davcrash** [flutter/flutter_clock#8]
I would like to know if i can manage the clock state with one of the next packages:

- https://pub.dev/packages/provider
- https://pub.dev/packages/flutter_bloc

And if it does, Does the size of the project affect the evaluation criteria?

**Comment by jkurtw** [comment]
Yes, you can use state management solutions and the size of the project doesn't matter for this contest.

**Comment by DrSensor** [comment]
@jkurtw 
Are other packages not related to state management allowed too? For example I want to use [flutter_hooks](https://pub.dev/packages/flutter_hooks) to declare my StatefulWidget.

Also, can I use packages that do code generation? (e.g [package:functional_widget](https://pub.dev/packages/functional_widget))

**Comment by jkurtw** [comment]
Yes, I don't see any issues with those, given they are both MIT license. 

For the code gen, as long as it is straight forward for the judges to upzip and run your submission it should be fine (e.g. no need to install other tools). This makes me realize we should add `flutter packages get` to the steps published in step 6 of the getting started section on flutter.dev/clock
